services:
  backend:
    # image: pharventory
    build:
      context: backend
      dockerfile: ./Dockerfile
    env_file:
      - backend/.env
    environment:
      NODE_ENV: production
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
    ports:
      - 3001:3001
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

# volumes:
#   redis-data:
